modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.jd_skill_tree]]
    modId="forge"
    mandatory=true
    versionRange="[47.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jd_skill_tree]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="jd_skill_tree"
version="${file.jarVersion}"
displayName="JD Skill Tree"
description="A data-driven skill tree mod."
